CREATE TABLE Categories (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    Description TEXT
);

CREATE TABLE Products (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    Description TEXT,
    CategoryId INTEGER NOT NULL,
    FOREIGN KEY (CategoryId) REFERENCES Categories (Id) ON DELETE CASCADE
);

CREATE TABLE ProductStocks (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    DateAdded DATETIME NOT NULL,
    Quantity INTEGER NOT NULL,
    ProductId INTEGER NOT NULL,
    FOREIGN KEY (ProductId) REFERENCES Products (Id) ON DELETE CASCADE
);

CREATE TABLE ProductPrices (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    DateSet DATETIME NOT NULL,
    Price DECIMAL(18, 2) NOT NULL,
    ProductId INTEGER NOT NULL,
    FOREIGN KEY (ProductId) REFERENCES Products (Id) ON DELETE CASCADE
);
